# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ca7f8254237f3a56798e167d9fe9fc8c4655bc9d04a5de29aeef23fea44813a9cb88938f9ec044b84c361ed747b5c386d1c01cba1e1c8003191018c9c0b19e6

test:
  secret_key_base: 8f111b381b194f739bd2f3ea6fc0927b1bfe9b881ebd0dffac4a48d65cd83336ab4e15b630a46e6ecccef5730d752b69eccb1e7d7ff99bdddc944b7c8a0d9f59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
